### ISSUE TITLE
Add a VERBOSE or DEBUG option

### ISSUE THREAD

**Issue by Quincunx271** [vector-of-bool/pmm#1]
It would be helpful if `pmm(...)` had a `VERBOSE` or `DEBUG` option so that it would output the executed processes before executing them:

```cmake
pmm(CONAN VERBOSE)
```

(when configuring cmake):

```
...
-- [pmm] Installing Conan requirements from /path/to/conanfile.txt
-- [pmm] conan install /path/to/conanfile.txt -s ... -o ...
...
```

This would help in understanding what pmm is doing under the hood.

**Comment by Quincunx271** [comment]
A thought: this could be a global variable:

```cmake
set(PMM_DEBUG TRUE)
pmm(CONAN)
```

That might better communicate that it's not intended to be turned on except for exploration or debug purposes

**Comment by vector-of-bool** [comment]
Committed, will be in next release
