### ISSUE TITLE
PMM can't find python installation on appveyor

### ISSUE THREAD

**Issue by AnotherFoxGuy** [vector-of-bool/pmm#10]
PMM can't find python on appveyor, but `find_package (Python)` is able to find python
Here are the python install locations: https://www.appveyor.com/docs/windows-images-software/#python

Test project: https://github.com/AnotherFoxGuy/pmm-appveyor
AppVeyor: https://ci.appveyor.com/project/AnotherFoxGuy/pmm-appveyor

**Comment by vector-of-bool** [comment]
Sorry that this took a while. 

In the meantime, I've moved my CI to Azure Pipelines, and also found the fix for this issue. It should be in the next release. Keep an eye out for it.

**Comment by vector-of-bool** [comment]
Published fix in 1.2.0
