### ISSUE TITLE
Question: Influence build type (Visual Studio)

### ISSUE THREAD

**Issue by Blubbz0r** [vector-of-bool/pmm#16]
Just played around with the project for the first time. Looks really promising!

One thing I would like to ask is what the best way to influence the build type for a Visual Studio build is? I did the following:

* added pmm.cmake (version 1.3.1)
* adjusted CMakeLists.txt:
```
include(pmm.cmake)
pmm(CONAN)
```
* Ran `cmake -G "Visual Studio 15 2017 Win64" ..\MyProject`
* The settings used by pmm for the conan install were:
```
[settings]
arch=x86_64
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
```
* I'm currently only interested in a Debug build though. What would I need to change to achieve that? I have added `SETTINGS "build_type=Debug"` to the `pmm` call and that works. However, it does not seem to be the ideal solution that every developer that wants a different build type has to change the project file?

**Comment by Quincunx271** [comment]
Visual Studio is a multi-configuration generator, so ideally there would be a way to set a multi-config generator for conan, but I don't think PMM has that.

If you set `CMAKE_BUILD_TYPE` on the cmake invocation, that would work: `cmake -G "Visual Studio 15 2017 Win64" ..\MyProject -DCMAKE_BUILD_TYPE=Debug`. PMM picks up on this and will forward it on to the `conan install` command.
