### ISSUE TITLE
Support older versions of CMake

### ISSUE THREAD

**Issue by Quincunx271** [vector-of-bool/pmm#2]
Ubuntu 16.04 is still very common. Its default version of CMake is 3.5.1. Is it reasonable to support CMake 3.5.1? That could allow more people to use pmm if they are unable to update CMake for some reason.

Not many changes are necessary. The `cmake_minimum_required`s need to be updated, obviously, and the `if(some_version VERSION_GREATER_EQUAL some_number)` need to be changed to `if(NOT some_version VERSION_LESS some_number)`. After that, I believe it works on CMake 3.5.1, although I have not tested all code paths.

**Comment by Quincunx271** [comment]
If this is worth supporting (i.e. it's unlikely we'll need features from a more modern CMake version), I can go ahead and submit a PR for it.

**Comment by vector-of-bool** [comment]
I'd like to support a rolling window of CMake versions, say "N minor versions behind stable." I don't want to get stuck on supporting 3.9 when CMake 4.5 is out and it has become the new CMake 2.6.

**Comment by Quincunx271** [comment]
I don't think this matters that much. If necessary, the user could host a backport repository where they backport to older CMake versions. That's also possible within this repo; we could have a branch for an older version of cmake, and mention that it's not very well supported. Either way, I'm closing this issue, because I don't think it's worth worrying over unless some user is willing to put in the work to maintain it.
