### ISSUE TITLE
Allow Custom Ports

### ISSUE THREAD

**Issue by cwfitzgerald** [vector-of-bool/pmm#21]
In the development of various of libraries, I end up with ports that are too unstable to be merge to upstream vcpkg (due to them needing to be changed multiple times a day). It would be great if pmm could offer a way to specify a custom ports folder and it would merge the ports from upstream vcpkg with the custom ones supplied. I haven't taken too good of a look yet on what would need to happen to make that work, but logically it shouldn't be too difficult, though knowing cmake, doing a recursive merge may be difficult.

**Comment by fradav** [comment]
I know it's little rude to ask the maintainer for this, but could you please merge the PR, I got a project which depends on this, and I don't want to go with my own fork + hand-made GitHub url in the main .cmake.

Regards,

**Comment by Quincunx271** [comment]
I recommend temporarily hosting pmm locally in your project. You can set the `PMM_URL` to be a `file:///` url, and have the updated implementation (perhaps trimmed to only include vcpkg) in your `cmake/` folder. This way, you can continue with whatever you're working on without being blocked, until vector-of-bool gets a chance to look at this.

**Comment by fradav** [comment]
I found even simpler than your suggestion: ```cmake
_pmm_set_if_undef(PMM_URL "https://raw.githubusercontent.com/AnotherFoxGuy/pmm/custom-ports/pmm")
```
In pmm.cmake. This just works.

**Comment by AnotherFoxGuy** [comment]
I've made a fork of PMM that includes all my pull request. 
if you want to use it you can replace the base URL with: 
`_pmm_set_if_undef(PMM_URL_BASE "http://anotherfoxguy.com/pmm/")`

**Comment by Pospelove** [comment]
Any progress on this?
