### ISSUE TITLE
PMM requires internet connection

### ISSUE THREAD

**Issue by Quincunx271** [vector-of-bool/pmm#8]
Once the files are already downloaded, PMM still requires an internet connection to download information about whether PMM is out-of-date. This should not be required. It should be possible to build without an internet connection.

With PMM 0.4.0 (but was told it wasn't changed in 1.0.0):

(CMakeTools Log)

```
[cmake] CMake Error at build/msvc-dbg/_pmm/0.4.0/entry.cmake:22 (message):
[cmake]   Error while downloading file from
[cmake]   'https://vector-of-bool.github.io/pmm/0.4.0/util.cmake' to
[cmake]   '/build-dir/_pmm/0.4.0/util.cmake'
[cmake]   [6]: "Couldn't resolve host name"
```

**Comment by vector-of-bool** [comment]
I'm unable to reproduce this one, actually?

**Comment by Quincunx271** [comment]
Steps to reproduce:

* Configure cmake in a fresh build directory, with internet connection
* Turn off the internet connection
* Re-configure cmake

Error message:

```
CMake Error at build/tmp/_pmm/1.0.1/entry.cmake:22 (message):
  Error while downloading file from
  'https://vector-of-bool.github.io/pmm/1.0.1/util.cmake' to
  '/path/to/build/tmp/_pmm/1.0.1/util.cmake'
  [6]: "Couldn't resolve host name"
Call Stack (most recent call first):
  build/tmp/_pmm/1.0.1/entry.cmake:37 (_pmm_download)
  pmm.cmake:65 (include)
  CMakeLists.txt:17 (include)
```
